- name: copy_es
  copy: src=elasticsearch-7.0.1.tar.gz dest=/opt/
- name: tar xf
  shell: tar xf /opt/elasticsearch-7.0.1.tar.gz -C /opt/
- name: copy_chown
  copy: src=chown.sh dest=/opt/
- name: chown elasticsearch-7.0.1
  shell: /bin/bash /opt/chown.sh
